### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [neolit123/qml-glsl-coder#1]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [a function like “ShaderItem::setSGNodeTexture”](https://github.com/neolit123/qml-glsl-coder/blob/08634c502924e87b89fedb263e3e17507664547f/cpp/shaderitem.cpp#L226 "Update candidate: ShaderItem::setSGNodeTexture()").

**Comment by neolit123** [comment]
feel free to send a PR. ;)
